/**
* This file is auto-generated by nestjs-proto-gen-ts
*/

import { Observable } from 'rxjs';
import { Metadata } from '@grpc/grpc-js';

export namespace city {
    export interface CityService {
        getById(
            data: GetByIdRequest,
            metadata?: Metadata,
            ...rest: any[]
        ): Observable<City>;
        getAll(
            data: EmptyRequest,
            metadata?: Metadata,
            ...rest: any[]
        ): Observable<City>;
    }
    export interface GetByIdRequest {
        id?: number;
    }
    // tslint:disable-next-line:no-empty-interface
    export interface EmptyRequest {
    }
    export interface City {
        id?: number;
        name?: string;
        country?: string;
        population?: number;
    }
}

