/**
* This file is auto-generated by nestjs-proto-gen-ts
*/

import { Observable } from 'rxjs';
import { Metadata } from '@grpc/grpc-js';

export namespace health {
    // tslint:disable-next-line:no-empty-interface
    export interface HealthCheckRequest {
    }
    export interface HealthCheckResponse {
        status?: string;
    }
    export interface Health {
        check(
            data: HealthCheckRequest,
            metadata?: Metadata,
            ...rest: any[]
        ): Observable<HealthCheckResponse>;
    }
}

